### ISSUE TITLE
UI Fix

### ISSUE THREAD

**Issue by heetboda10** [Alitindrawan24/Binary-Calculator#1]
It look like the calculator needs some UI fix so that it looks a little better for the user. Please assign this to me.

**Comment by Alitindrawan24** [comment]
> It look like the calculator needs some UI fix so that it looks a little better for the user. Please assign this to me.

Okay this issue already assigned to you

**Comment by V3ntus** [comment]
Check my recent commit https://github.com/Alitindrawan24/Binary-Calculator/pull/2
