### ISSUE TITLE
entering input directly

### ISSUE THREAD

**Issue by govind2404** [Alitindrawan24/Binary-Calculator#10]
now, the user has to click on button numerous times to give the operands. I would like to make that happen through keyboard.

**Comment by Alitindrawan24** [comment]
> now, the user has to click on button numerous times to give the operands. I would like to make that happen through keyboard.

Yeah that's is an issue, are you want to solve this issue?

**Comment by V3ntus** [comment]
> > Keyboard support has already been added #3
> 
> Yes but only work on numpad, some keyboard doesn't have numpad

Support was also added for the number bar above the keys, not just numpad

**Comment by Alitindrawan24** [comment]
> > > Keyboard support has already been added #3
> > 
> > 
> > Yes but only work on numpad, some keyboard doesn't have numpad
> 
> Support was also added for the number bar above the keys, not just numpad. But I hear your issue

Okay, but I already fix this by adding some conditions in the event listener. Thanks
