### ISSUE TITLE
Spelling Error for 'Calculator' and Missing Favicon on Home Page

### ISSUE THREAD

**Issue by ayushsingh199** [Alitindrawan24/Binary-Calculator#113]
There are two issues on the home page:
1. The word **"Calculator"** is spelled incorrectly.
2. The favicon is missing from the browser tab.

#### Steps to Reproduce
1. Open the home page.
2. Check the spelling of "Calculator."
3. Notice the missing favicon in the browser tab.

#### Expected Behavior
- The word "Calculator" should be spelled correctly across the website.
- A favicon should be visible on the browser tab for better branding and user experience.
<img width="457" alt="Screenshot 2024-10-15 at 9 55 07 AM" src="https://github.com/user-attachments/assets/0c7bb67d-f77c-4c97-86cf-08d2c741f3d4">
<img width="106" alt="Screenshot 2024-10-15 at 9 55 26 AM" src="https://github.com/user-attachments/assets/3d5cb279-c10a-4f3e-8420-8da60cce2ebe">

**Comment by Alitindrawan24** [comment]
I think issue no 1 is already fixed but no 2 can be fixed. I will assign this issue to you
