### ISSUE TITLE
Enhancing UI

### ISSUE THREAD

**Issue by nidhi752** [Alitindrawan24/Binary-Calculator#122]
Hello,  
I’ve noticed that the calculator on my webpage isn’t fitting properly within a single view, which forces users to scroll up and down repeatedly while performing calculations. This issue disrupts the overall user experience and makes it inconvenient to use the calculator efficiently. To improve this, I would like to modify the layout and design so that the entire calculator fits within the visible screen area by default. My goal is to create a seamless, user-friendly experience that allows users to carry out calculations without the need for unnecessary scrolling.
Please assign this issue to me under hackoctoberfest'24
Thankyou

**Comment by Alitindrawan24** [comment]
Ok @nidhi752 already assigned
