### ISSUE TITLE
Theme change option not working and favicon addition needed

### ISSUE THREAD

**Issue by Abhishek-IITP** [Alitindrawan24/Binary-Calculator#134]
The following issues were found on the binary calculator site:

**Theme Change Option:**

1. The theme change option currently isn't functional. Clicking the theme switch does not alter the appearance of the site as expected. 2. This issue affects the overall user experience, as users are unable to switch between light and dark themes (or other available themes).

 **Investigate and fix the theme toggle functionality.**

1.  Ensure proper loading and switching of styles based on user selection.

**Favicon Addition:**

1. The site currently lacks a favicon. This is a small but important element that enhances the site's branding and improves the overall look, especially when users have multiple tabs open.

**Comment by Alitindrawan24** [comment]
Already assigned @Abhishek-IITP
