### ISSUE TITLE
Button's size needs to get fixed

### ISSUE THREAD

**Issue by shreya-paul-17** [Alitindrawan24/Binary-Calculator#136]
The text of operations that is being performed is not clearly visible in some buttons. I would like to fix that so that the text on the buttons don't look congested.

Here is a screenshot for reference marked in yellow color:
![binary-cal](https://github.com/user-attachments/assets/231f1e42-d9d4-4820-9bd4-57ad4541cc46)

Kindly assign the task to me

**Comment by Alitindrawan24** [comment]
@shreya-paul-17 already assigned
