### ISSUE TITLE
[BUG] : Footer UI Issue

### ISSUE THREAD

**Issue by Artemiskgg1** [Alitindrawan24/Binary-Calculator#138]
![image](https://github.com/user-attachments/assets/e725a1d3-c6d9-493f-a5e6-a51f27c4d905)
The footer is aligned with the bottom screen.
I can be improved by adjusting the CSS Styles.
@Alitindrawan24 please assign this issue to me under hacktoberfest.
Thank You!

**Comment by Alitindrawan24** [comment]
@Artemiskgg1 already assigned
