### ISSUE TITLE
Add Tooltips to Calculator Buttons for Improved User Understanding

### ISSUE THREAD

**Issue by ShikariSohan** [Alitindrawan24/Binary-Calculator#139]
Currently, some calculator buttons (e.g., the button for finding gray code) are not clearly labeled, which may confuse users. To enhance the user experience and provide a clearer understanding of each button's functionality, add tooltips to all calculator buttons. These tooltips should display brief descriptions of the buttons' actions when hovered over, ensuring users can easily grasp the purpose of each button without additional context.

**Comment by ShikariSohan** [comment]
@Alitindrawan24 Please assign me for it.

**Comment by Alitindrawan24** [comment]
@ShikariSohan already assigned
