### ISSUE TITLE
[BUG]: Missing one button in UI

### ISSUE THREAD

**Issue by SubramanyaKS** [Alitindrawan24/Binary-Calculator#143]
Hi @Alitindrawan24 , there is no button of comma(,) present in button tab which is required for AND OR XOR operation.
I can include that please assign me this issue under hacktoberfest.
Thank You
Below is the image of existing app.
![image](https://github.com/user-attachments/assets/611b3a72-d889-4710-bbe3-49484b2de448)

**Comment by Alitindrawan24** [comment]
already assigned @SubramanyaKS
