### ISSUE TITLE
Alignment of the close button 

### ISSUE THREAD

**Issue by shreya-paul-17** [Alitindrawan24/Binary-Calculator#148]
The close button is placed exactly to the side of the result in the description bar. We can adjust it to the right side and create some hovering effects for users to understand more clearly.

Here is a screenshot for reference marked in orange color:
![cal2](https://github.com/user-attachments/assets/c06cf29b-2531-43b7-97b6-fa9640400f5b)

@Alitindrawan24 kindly assign me this task

**Comment by Alitindrawan24** [comment]
@shreya-paul-17 already assigned
