### ISSUE TITLE
In Dark Mode the Output Section is also in dark theme

### ISSUE THREAD

**Issue by Harshcbx8** [Alitindrawan24/Binary-Calculator#156]
![Screenshot 2024-10-22 113035](https://github.com/user-attachments/assets/97ef5e43-3c44-43d3-bd9a-5dd88d1229f0)

In your calc website the output section have to be dark theme with dark mode, Yet is shows white box and black text, I will fix this issue Please assign it to me!

**Comment by ritikraj2425** [comment]
@Alitindrawan24 please assign this issue to me

**Comment by Harshcbx8** [comment]
@ritikraj2425 Bro find out your own issue! I have noticed that issue so that was me first to resolve it!

**Comment by Alitindrawan24** [comment]
@ritikraj2425 you can raise another issue

**Comment by Alitindrawan24** [comment]
> @ritikraj2425 you can raise another issue

Or you can comment on another issue that not assigned yet and request to solve it from the issue owner
