### ISSUE TITLE
Complement Button

### ISSUE THREAD

**Issue by AdityaKumar2408** [Alitindrawan24/Binary-Calculator#17]
I want to add buttons like 1's complement and 2's complement in this.

**Comment by Alitindrawan24** [comment]
@AdityaKumar2408 Can you explain the compliment button that you mean ?

**Comment by AdityaKumar2408** [comment]
@Alitindrawan24 Sorry, type, its complement not compliment

**Comment by AdityaKumar2408** [comment]
Basically 1's complement is : 0100 => 1011
and 2's complement is : 1's compliment +1

**Comment by Alitindrawan24** [comment]
Ahh I see, ok I will assign this issue to you. Thank you
