### ISSUE TITLE
Adding And , Or , Xor operator 

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Alitindrawan24/Binary-Calculator#19]
Adding add(&)  , or [ | ]  , Xor   [ ^ ] operators.

Please assign this under hacktoberfest_23 and Please label this : )

**Comment by Alitindrawan24** [comment]
> Adding add(&) , or [ | ] , Xor [ ^ ] operators.
> 
> Please assign this under hacktoberfest_23 and Please label this : )

Assign the issue to hacktoberfest_23 ? why ?

**Comment by Bharath-KumarReddy** [comment]
I am asking that , assign this issue to me as a contributor to hacktoberfest_23 : )

**Comment by 07-Chandra** [comment]
could please assign this to me if not solved ?

**Comment by Alitindrawan24** [comment]
> could please assign this to me if not solved ?

Yes of course, you can open a PR about this issue and if accepted I will change the assigne to @07-Chandra

**Comment by Bharath-KumarReddy** [comment]
Hey , I had a PR #62 All binary operations will work once please check : )
