### ISSUE TITLE
Lack of error messages/Input Validation 

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Alitindrawan24/Binary-Calculator#21]
### Lack of Error Messages

The binary calculator currently lacks error messages when incorrect input is provided, resulting in the input field being cleared without any explanation. This can be confusing for users, as it doesn't provide guidance on what went wrong.

**Example:**

```plaintext
Input: ++-
Expected: Display an error message explaining the incorrect input.
Current: Input field is cleared without any error message.
```

**Additional**
I would like to work on this issue, kindly assign.

**Comment by Alitindrawan24** [comment]
Interesting, I will assign this issue to you @ayushichoudhary-19 Thank you

**Comment by ayushichoudhary-19** [comment]
https://github.com/Alitindrawan24/Binary-Calculator/pull/25 Closes this issue.
