### ISSUE TITLE
Handling Division by Zero

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Alitindrawan24/Binary-Calculator#22]
The calculator crashes when attempting to divide by zero, causing the website to hang on reload. This behavior is inconsistent with other aspects of the application, where it should ideally display an appropriate message and gracefully handle divide by zero cases without impacting user experience.

**Example:**

1. Input: `1101 / 0`
   - Expected: The calculator should handle division by zero gracefully.
   - Current: The website crashes and becomes unresponsive upon reloading.

**Steps to Recreate:**

1. Open the binary calculator on the website.
2. Enter a binary expression that involves dividing by zero, such as `1101 / 0`.
3. Press the "=" button to perform the division.
4. Observe that the website crashes and becomes unresponsive upon reloading.

**Expected Behavior:**

The calculator should detect the divide by zero condition, handle it gracefully, and provide appropriate feedback to the user without crashing the website.

This issue impacts user experience and should be addressed to ensure the calculator functions smoothly.

---

**Note:** I would like to work on this issue. Please assign it to me.

**Comment by Alitindrawan24** [comment]
Ahh I see, I will assign this issue to you. Thank you
