### ISSUE TITLE
 Add Theme Toggle Feature Dark Theme and Default Theme with Animations

### ISSUE THREAD

**Issue by utsxvrai** [Alitindrawan24/Binary-Calculator#24]
I would like to request the implementation of a theme toggle feature in the project. Currently, there is a need for users to switch between light and dark themes, and having a dedicated button for this would greatly enhance the user experience.

@Alitindrawan24 pls assign this issue to me, i have already implemented it!

https://github.com/Alitindrawan24/Binary-Calculator/assets/116128086/31f5b0c2-604e-456c-b2c1-7c786cb245e9

**Comment by utsxvrai** [comment]
and pls add it to the HacktoberFest Tag!!

**Comment by Alitindrawan24** [comment]
Amazing UI, I already assigned to you @utsxvrai Thank you
