### ISSUE TITLE
feature : Add a backspace button

### ISSUE THREAD

**Issue by debghs** [Alitindrawan24/Binary-Calculator#28]
The calculator currently has a 'C' button that clears the whole input, if clicked.
I want to add a backspace button that would omit the last character of the input stream.

Also, I would like to rearrange the existing buttons for aesthetic purposes.
If you wish I may work on that too.

I have added the necessary code and now the project looks like this,

![image](https://github.com/Alitindrawan24/Binary-Calculator/assets/145260557/2c930d4e-1552-4d98-b3c3-10ed5fd29176)

Do you wish me to create a PR for you to merge this ??

**Comment by Alitindrawan24** [comment]
Yes I think we need backspace button to delete the last number, I will assign this to you. Thank you
