### ISSUE TITLE
bug : non-binary fraction output

### ISSUE THREAD

**Issue by debghs** [Alitindrawan24/Binary-Calculator#31]
The calculator outputs decimal numbers in fractions instead of only binary numbers when attempting to divide a number by a larger number.

Example:

Input: 11 / 101
Current: 0.33333333...
Expected: 0.10011001100....

The calculator should output only binary digits in case of a binary fraction.

May I work on this issue ??

**Comment by Alitindrawan24** [comment]
Yes of course, I will assign this issue to you. Thank you
