### ISSUE TITLE
Would like to Implement memory functionality, allowing users to store and recall previous calculations. Assign this issue to me as hacktoberfest2023

### ISSUE THREAD

**Issue by kondapalli19** [Alitindrawan24/Binary-Calculator#34]

**Comment by Alitindrawan24** [comment]
Can you explain more specific about the memory functionality? is like history ?

**Comment by kondapalli19** [comment]
Indeed, when a user clicks the button after a calculation, the current result (displayed on the calculator) is stored in the memory slot. When a user clicks the (Memory Recall) button, the value stored in the memory slot is displayed on the calculator's screen, allowing the user to use it in a calculation or view it. For example, if they previously calculated 10 + 5 and stored the result in memory (resulting in a memory value of 15), they can recall the memory value and add it to a new calculation, like 15 + 7 even after in the middle you have done many calculations.
1. No need to remember the result which will be used later.
2. Directly operate it

**Comment by Alitindrawan24** [comment]
Interesting, I will assign this issue to you @kondapalli19 Thank you
