### ISSUE TITLE
Displaying Correct Binary to Decimal Conversion

### ISSUE THREAD

**Issue by pranav-jadhav** [Alitindrawan24/Binary-Calculator#36]
Currently, there is an no functionality to display the binary to decimal conversion functionality in the application. When users input a binary number, the application does not display the decimal equivalent. This can be resolved to ensure accurate conversions and provide users with the correct results.

**Comment by Alitindrawan24** [comment]
Interesting, can you solve this issue ? I will assign this to you. Thank you
