### ISSUE TITLE
Clearing the input on entering new input after invalid input message

### ISSUE THREAD

**Issue by vaibhava17** [Alitindrawan24/Binary-Calculator#38]
<img width="613" alt="image" src="https://github.com/Alitindrawan24/Binary-Calculator/assets/65801959/e48d5ccd-2dd5-4e5b-9f5a-d5a35d87bd62">

Whats happing is when user is entering an invalid input the calculator show the invalid input result on the screen but it is not clearing when entering new input number. Need to clear before enter manually.

What i will do is that when this message is showing i will allow input field to get clear automatically when a new digit is entered from the keyboard without manually clearing the field for next solution.

**Comment by shivamsinghcse** [comment]
"I would like to address and work on this particular issue. Could you please assign me to this task?

**Comment by Alitindrawan24** [comment]
@vaibhava17 Can you solve and work to this issue ? Or I can assign into @shivamsinghcse ? Thank you

**Comment by vaibhava17** [comment]
I can work on it

**Comment by Alitindrawan24** [comment]
Okay I will assign to @vaibhava17

**Comment by Alitindrawan24** [comment]
@Villain45 Yeah I think another PR before already implement this, if you think so you can close this is issue too
