### ISSUE TITLE
Reorganize Button Layout 

### ISSUE THREAD

**Issue by vaishnavibn14** [Alitindrawan24/Binary-Calculator#48]
![image](https://github.com/Alitindrawan24/Binary-Calculator/assets/75124124/d3a0cd96-2b7c-4bf9-aab9-181e1c74aa4a)

The current Button Layout is very jumbled and non-intuitive. I would like to rearrange the button layout and make it more friendly.

Proposed Solution: 

Arrange the buttons in a way that is similar to most of the calculator layouts. 

Please assign me this issue under the HacktoberFest tag.

**Comment by Alitindrawan24** [comment]
Nice idea, I already assign this issue to you. Thank you

**Comment by Alitindrawan24** [comment]
Merged
