### ISSUE TITLE
Binary to Octal Conversion

### ISSUE THREAD

**Issue by vaishnavibn14** [Alitindrawan24/Binary-Calculator#49]
Currently, there is an no functionality to display the binary to octal conversion in the application. 

I would like to add a button that converts the binary number to octal number and displays it.

**Comment by Alitindrawan24** [comment]
I think the update will break the calculator if the octal value is displayed in the calculator. Can you make the display on popup modal or something else that not break the calculator functionality ?

**Comment by vaishnavibn14** [comment]
Yes I can do that. Do you want a alert or a small pop up?

**Comment by Alitindrawan24** [comment]
Yes, you can select one of them, and also this issue is similar to #50 so maybe the update will look similar too with different octal and hexadecimal only. I hope the decision is the same if using an alert or a small pop-up. Thank you

**Comment by Alitindrawan24** [comment]
Merged
