### ISSUE TITLE
Displaying Correct Binary to Hexadecimal Conversion

### ISSUE THREAD

**Issue by pranav-jadhav** [Alitindrawan24/Binary-Calculator#50]
Currently, there is an no functionality to display the binary to hexadecimal conversion functionality in the application. When users input a binary number, the application cannot display the hexadecimal equivalent. 

I would like to add a hexadecimal button.

**Comment by Alitindrawan24** [comment]
I think the update will break the calculator if the hexadecimal value is displayed in the calculator. Can you make the display on popup modal or something else that not break the calculator functionality ?

**Comment by pranav-jadhav** [comment]
Yes, I can do that. Do you want a small pop up or just want me to display an alert?

**Comment by Alitindrawan24** [comment]
Yes, you can select one of them, and also this issue is similar to #49 so maybe the update will look similar too with different octal and hexadecimal only. I hope the decision is the same if using an alert or a small pop-up. Thank you

**Comment by vaishnavibn14** [comment]
@pranav-jadhav You can use the same code for pop up #49.

**Comment by pranav-jadhav** [comment]
@vaishnavibn14 
Sounds good
Let me know once you are done

**Comment by Sanketh149** [comment]
@pranav-jadhav Please check my PR and merge it. Thank You
