### ISSUE TITLE
addition of Bitwise Shift with Carry (Rotate) operation

### ISSUE THREAD

**Issue by ctln23** [Alitindrawan24/Binary-Calculator#64]
It will perform a bitwise shift operation with carry (rotation) for circular shifts.

**Comment by ctln23** [comment]
@Alitindrawan24 I would like to work on this. Kindly assign it to me

**Comment by Alitindrawan24** [comment]
> @Alitindrawan24 I would like to work on this. Kindly assign it to me

Yes of course
