### ISSUE TITLE
removal of unloaded image packet

### ISSUE THREAD

**Issue by blunterdecosta123** [Alitindrawan24/Binary-Calculator#68]
In the ERR box there is appearing an unwanted unloaded image which not visually appealing  i want to remove it
<img width="1280" alt="Screenshot 2024-10-11 at 10 39 45 AM" src="https://github.com/user-attachments/assets/27e37c87-1b68-40fa-b3a9-c3dce8554a49">
Please assign me this issue under Hacktoberfest 2024!!!

**Comment by Rishabh32700** [comment]
@blunterdecosta123 i can work on this can u plz assign this issue to me

**Comment by Rishabh32700** [comment]
i have created PR  #69 can u plz review and merge
