### ISSUE TITLE
Adding more functionalities in the calculator

### ISSUE THREAD

**Issue by sidgureja7803** [Alitindrawan24/Binary-Calculator#70]
1 -  Logical AND, OR, XOR Operations: Allow users to perform bitwise logical operations between two binary numbers.
2 -  Binary to Gray Code Conversion: Allow conversion between binary and Gray code, commonly used in digital systems.
3 - Signed and Unsigned Binary Interpretation: Show the signed and unsigned interpretation of a binary number.
4 - Binary Floating-Point Representation: Allow users to input floating-point numbers and convert them to their binary IEEE 754 format.
5 - Parity Bit Calculation: Calculate and show the parity bit (even/odd) for error detection.

**Comment by sidgureja7803** [comment]
@Alitindrawan24 please assign this issue to me

**Comment by Alitindrawan24** [comment]
@sidgureja7803 Issue already assigned, you can work with at least 1 option in this issue. Thank you
