### ISSUE TITLE
Changing background.

### ISSUE THREAD

**Issue by taneeshaa15** [Alitindrawan24/Binary-Calculator#76]

**Comment by Pratham-Onkar-Singh** [comment]
Please give more details about this issue and assign this to me.

**Comment by taneeshaa15** [comment]
@Alitindrawan24 I opened this issue and now assign this issue to me under hacktoberfest.

**Comment by Alitindrawan24** [comment]
can you explain what would you do in this issue ? @taneeshaa15

**Comment by taneeshaa15** [comment]
@Alitindrawan24  This background looks messy, I will change the colors and make it look more good.

**Comment by Alitindrawan24** [comment]
Can you attach the new background here ? If it look more better I will assign the issue @taneeshaa15

**Comment by Alitindrawan24** [comment]
Ok look interested, already assigned @taneeshaa15
