### ISSUE TITLE
Add Bitwise NOT Operator to Binary Calculator

### ISSUE THREAD

**Issue by Satyasn01** [Alitindrawan24/Binary-Calculator#79]
The current implementation of the Binary Calculator lacks the bitwise NOT operator (~), which is essential for performing complete binary arithmetic and logical operations. The bitwise NOT operation is crucial in computing for inverting binary digits.

Proposal

I propose adding a button labeled ‘~’ to perform the bitwise NOT operation. This addition will allow users to easily invert all bits of the current binary number displayed in the calculator.

Importance

Integrating the bitwise NOT operator will enhance the calculator’s functionality, making it more versatile and useful for educational purposes, debugging, and binary arithmetic tasks. This feature is fundamental to ensuring a complete set of binary operations are available to users.

Assignment and Labels

I would like to be assigned to this issue and suggest adding the labels “hacktoberfest” and “hacktoberfest-accepted” to acknowledge the contribution towards open source and Hacktoberfest.

Tagging Reviewers

Requesting review and assignment from @Alitindrawan24 to discuss the feasibility and implementation of this feature.

**Comment by Alitindrawan24** [comment]
@Satyasn01 already assigned
