### ISSUE TITLE
Fix the javascript function  of calculator .

### ISSUE THREAD

**Issue by NinjaMandy** [Alitindrawan24/Binary-Calculator#8]
i think the js Function have Bug or  something is wrong with it , it show 1+1 =10  and 1/0 broke the application, fix this answer Zero is not showing , like = 1*0 = empty . 

please don't change the whole, function try to solve with minor changes .

**Comment by Alitindrawan24** [comment]
> i think the js Function have Bug or something is wrong with it , it show 1+1 =10 and 1/0 broke the application, fix this answer Zero is not showing , like = 1*0 = empty .
> 
> please don't change the whole, function try to solve with minor changes .

It's a binary calculator, that's why 1 + 1 = 10 because 10 is binary from 2
