### ISSUE TITLE
ADDITION OF FEEDBACK SECTION

### ISSUE THREAD

**Issue by taniya542** [Alitindrawan24/Binary-Calculator#82]
To link a feedback form to a button, allowing users to provide insightful feedback, which will be useful for enhancing the website's viability.

**Comment by Alitindrawan24** [comment]
@taniya542 where would you place the feedback button ?

**Comment by sharma-mohit-codes** [comment]
@Alitindrawan24 assign this issue to me and also i would add the feedback form below the calculator body and above made with love line

**Comment by sharma-mohit-codes** [comment]
@Alitindrawan24 I have also created a PR for it already as #160 , please look into it and merge
