### ISSUE TITLE
Bug: Switching to Dark-mode changes the design of the buttons and also the Font.

### ISSUE THREAD

**Issue by Pratham-Onkar-Singh** [Alitindrawan24/Binary-Calculator#84]
Issue Description: When switching to dark mode, the design of the buttons and the font style undergoes unexpected changes. This affects the visual consistency and readability of the UI elements, as seen in the attached screenshot.

Expected Behavior: Switching to dark mode should retain the original design of the buttons and the font. The theme should only alter changes appropriate for dark mode without affecting other design elements.

Steps to Recreate:
- Go to the website Binary Calculator.
- Switch from light mode to dark mode using theme-icon button.
- Observe that the icons and font change in design, which should remain consistent.

Screenshot: Please refer to the attached screenshot for reference.
![binarycalculator](https://github.com/user-attachments/assets/b56eab13-96fd-42f4-876c-e03fdfac3826)

Request: Kindly assign this issue to me (Pratham Onkar Singh) so I can resolve it.

**Comment by namansharma3007** [comment]
I can handle this issue. Please assign it to me

**Comment by namansharma3007** [comment]
Please add hacktoberfest tags

**Comment by Pratham-Onkar-Singh** [comment]
@Alitindrawan24 Please do assign this issue to me (Pratham Onkar Singh) so that i can resolve it.

**Comment by Alitindrawan24** [comment]
@Pratham-Onkar-Singh already assigned
