### ISSUE TITLE
Change the CSS styling of the webpage

### ISSUE THREAD

**Issue by barunipriyats** [Alitindrawan24/Binary-Calculator#9]
Hi @Alitindrawan24 I would like to change the CSS styling of the webpage by make the page attractive & easy-readable to the user. I am good in this kind of issue. Please assign this task to me. Thank you.

**Comment by Alitindrawan24** [comment]
> Hi @Alitindrawan24 I would like to change the CSS styling of the webpage by make the page attractive & easy-readable to the user. I am good in this kind of issue. Please assign this task to me. Thank you.

Okay, I will assign the issue to you
