### ISSUE TITLE
Add Landing page 

### ISSUE THREAD

**Issue by Prachirsh** [Alitindrawan24/Binary-Calculator#91]
Landing page help user's to understand about Binary languages who are new to learn and explore it will make website attractive and user friendly.
I would like to work on it. Can you assign it to me?

**Comment by Alitindrawan24** [comment]
is the landing page on different page ?

**Comment by Prachirsh** [comment]
Yes first landing page will be there and then the main page will open

**Comment by Alitindrawan24** [comment]
@Prachirsh already assigned
