### ISSUE TITLE
Design Issue: In Dark-mode Text "Made with (heart)" changes its design and has no hover effect.

### ISSUE THREAD

**Issue by Pratham-Onkar-Singh** [Alitindrawan24/Binary-Calculator#92]
Issue Description: When switching to dark mode, the text "Made with ❤" at the footer of the website changes its design unexpectedly. This affects the visual style, making it inconsistent with the rest of the page's design in dark mode.It also does not have same hovering effect as in normal mode.

Expected Behavior: The text "Made with (heart)" should retain its original font and design when switching to dark mode. It should also retain the same hovering effect as in normal mode. Only color adjustments should occur to make it suitable for dark mode without altering the design.

Steps to recreate:

- Go to the website Binary Calculator.
- Scroll down to the footer where the text "Made with ❤" is located.
- Switch from light mode to dark mode.
- Observe the design change in the text and hover effect which should remain visually consistent.

![binary](https://github.com/user-attachments/assets/27012b9a-e569-4903-90a2-c4335ad4c655)

Request: Kindly assign this issue to me (Pratham Onkar Singh) so I can resolve it.

**Comment by Pratham-Onkar-Singh** [comment]
@Alitindrawan24  Please do assign this issue to me(Pratham Onkar Singh) so that i can resolve it as soon as possible.

**Comment by Alitindrawan24** [comment]
Already assigned @Pratham-Onkar-Singh
